export const buildingsData = {
  // for melee
  swordsmithy: {
    name: "Swordsmithy",
    nameSymbol: "🗡️",
    underConstruction: false,
    constructed: false,
    tier: 1,
    attackBonus: 2,
    healthBonus: 2,
    description: "Melee units gain +2 to attack, +2 to health.",
    health: 2,
    woodCost: 10,
    stoneCost: 10,
    metalCost: 0,
    freeworkerCost: 5,
  },
  // for pewpew
  // TODO: Rename as "archery hut"
  archeryHut: {
    name: "Archery Hut",
    nameSymbol: "🎯",
    underConstruction: false,
    constructed: false,
    tier: 1,
    attackBonus: 3,
    healthBonus: -1,
    // include flavourtext about the divine knowledge given
    description: "Pewpew units gain +3 to attack but -1 health.",
    health: 2,
    woodCost: 10,
    stoneCost: 0,
    metalCost: 10,
    freeworkerCost: 5,
  },
  // for tanky
  armorsmithy: {
    name: "Armorsmithy",
    nameSymbol: "🛡️",
    underConstruction: false,
    constructed: false,
    tier: 1,
    attackBonus: 1,
    healthBonus: 3,
    description: "Tanky units gain +1 to attack, +3 to health.",
    health: 2,
    woodCost: 0,
    stoneCost: 10,
    metalCost: 10,
    freeworkerCost: 5,
  },
  // for all units
  mealHall: {
    name: "Meal Hall",
    nameSymbol: "🍖",
    underConstruction: false,
    constructed: false,
    tier: 1,
    attackBonus: 0,
    healthBonus: 2,
    armorBonus: 0,
    description: "All units gain +2 to health, +2 to armor.",
    health: 2,
    woodCost: 10,
    stoneCost: 10,
    metalCost: 10,
    freeworkerCost: 5,
  },
  healingChamber: {
    name: "Healing Chamber",
    nameSymbol: "🩸",
    underConstruction: false,
    constructed: false,
    tier: 1,
    attackBonus: 0,
    healthBonus: 0,
    armorBonus: 0,
    description: "Heals units after combat.",
    health: 2,
    woodCost: 10,
    stoneCost: 10,
    metalCost: 10,
    freeworkerCost: 5,
  },
  // for all units
  townCenter: {
    name: "Town Center",
    nameSymbol: "🏙️",
    /* FIXME: Path not working */
    imageSrc: "/images/town-center-01.png",
    underConstruction: false,
    constructed: true,
    tier: 1,
    attackBonus: 0,
    description: "Losing this building means game over!",
    healthBonus: 0,
    health: 3,
    woodCost: 0,
    stoneCost: 0,
    metalCost: 0,
    freeworkerCost: 0,
  },
  scoutUnit: {
    name: "Scout Unit",
    nameSymbol: "🔍",
    underConstruction: false,
    constructed: false,
    tier: 1,
    attackBonus: 0,
    description: "Upgrade intel on the enemy army.",
    healthBonus: 0,
    health: 2,
    woodCost: 15,
    stoneCost: 15,
    metalCost: 15,
    freeworkerCost: 10,
  },
};

export const buildingCostsData = {
  swordsmithy: {
    freeworkers: 5,
    wood: 10,
    stone: 10,
    metal: 0,
  },
  // for pewpew
  archeryHut: {
    freeworkers: 5,
    wood: 10,
    stone: 0,
    metal: 10,
  },
  // for tanky
  armorsmithy: {
    freeworkers: 5,
    wood: 0,
    stone: 10,
    metal: 10,
  },
  // for all units
  mealHall: {
    freeworkers: 5,
    wood: 10,
    stone: 10,
    metal: 10,
  },
  healingChamber: {
    freeworkers: 5,
    wood: 10,
    stone: 10,
    metal: 10,
  },
  // for all units
  townCenter: {
    freeworkers: 0,
    wood: 0,
    stone: 0,
    metal: 0,
  },
  scoutUnit: {
    freeworkers: 10,
    wood: 15,
    stone: 15,
    metal: 15,
  },
};
