/* TODO: Add a building which adds to number of workers per turn */

export const buildingsData = {
  // for all units
  townCenter: {
    name: "Town Center",
    symbol: "🏙️",
    /* FIXME: Path not working */
    imageSrc: "/images/town-center-01.png",
    enabled: false,
    underConstruction: false,
    constructed: true,
    tier: 1,
    /* attackBonus: 0,
    healthBonus: 0, */
    description: "Losing this building means game over!",
    buildScore: 0,
    bgImage: "bg-townCenter",
    maxHealth: 15,
    currentHealth: 15,
    damage: 0,
    resourceCosts: {},
    unlockedUnit: "farmer",
  },
  // for fighter
  swordsmithy: {
    name: "Swordsmithy",
    symbol: "🗡️",
    // "enabled" means it can be seen in the game. This feature is not yet active.
    // Maybe all additional buildings become available to unlock after their first combat?
    enabled: true,
    underConstruction: false,
    constructed: false,
    tier: 1,
    /* attackBonus: 2,
    healthBonus: 2, */
    description: "Craft swords. Unlock Fighters.",
    bgImage: "bg-swordsmithy",
    maxHealth: 15,
    currentHealth: 15,
    damage: 0,
    resourceCosts: { workers: 5, wood: 10, stone: 10 },
    buildScore: 50,
    unlockedUnit: "fighter",
  },
  // for archer
  archeryHut: {
    name: "Archery Hut",
    symbol: "🎯",
    enabled: false,
    underConstruction: false,
    constructed: false,
    tier: 1,
    /* attackBonus: 3,
    healthBonus: -1, */
    description: "Learn ranged combat. Unlock Archers.",
    bgImage: "bg-archeryHut",
    maxHealth: 15,
    currentHealth: 15,
    damage: 0,
    resourceCosts: { workers: 5, wood: 15, metal: 10 },
    buildScore: 50,
    unlockedUnit: "archer",
  },
  // for knight
  smelter: {
    name: "Smelter",
    symbol: "🛡️",
    enabled: false,
    underConstruction: false,
    constructed: false,
    tier: 1,
    /* attackBonus: 1,
    healthBonus: 3, */
    description: "Learn to smelt metals. Unlock Knights.",
    bgImage: "bg-smelter",
    maxHealth: 15,
    currentHealth: 15,
    damage: 0,
    resourceCosts: { workers: 5, stone: 15, metal: 15 },
    buildScore: 50,
    unlockedUnit: "knight",
  },
  // for mages
  mageSchool: {
    name: "Mage School",
    symbol: "🔮",
    enabled: false,
    underConstruction: false,
    constructed: false,
    tier: 1,
    /* attackBonus: 1,
    healthBonus: 3, */
    description: "Learn magic! Unlock Mages.",
    bgImage: "bg-mageSchool",
    maxHealth: 15,
    currentHealth: 15,
    damage: 0,
    resourceCosts: { workers: 5, stone: 15, metal: 10, crystal: 5 },
    buildScore: 75,
    unlockedUnit: "mage",
  },
  // for bombirds
  explosivesResearch: {
    name: "Explosives Research",
    symbol: "🔥",
    enabled: false,
    underConstruction: false,
    constructed: false,
    tier: 1,
    /* attackBonus: 1,
    healthBonus: 3, */
    description: "Explosives go boom! Unlock Bombirds.",
    bgImage: "bg-explosivesResearch",
    maxHealth: 5,
    currentHealth: 5,
    damage: 0,
    resourceCosts: { workers: 5, wood: 15, stone: 15, metal: 10, crystal: 10 },
    buildScore: 100,
    unlockedUnit: "bombird",
  },
  // add workers
  qualityHousing: {
    name: "Quality Housing",
    symbol: "🏘️",
    enabled: false,
    underConstruction: false,
    constructed: false,
    tier: 1,
    /* attackBonus: 0,
    healthBonus: 2, */
    description: "Increase the number of workers available.",
    bgImage: "bg-qualityHousing",
    maxHealth: 20,
    currentHealth: 20,
    damage: 0,
    resourceCosts: { workers: 5, wood: 10, stone: 10, metal: 10 },
    buildScore: 50,
    // how many extra workers it provides once constructed -- tweak as necessary
    workerBonus: 5,
  },
  // for all units
  mealHall: {
    name: "Meal Hall",
    symbol: "🍖",
    enabled: false,
    underConstruction: false,
    constructed: false,
    tier: 1,
    /* attackBonus: 0,
    healthBonus: 2, */
    description: "All units gain +2 to health, +2 to armor.",
    bgImage: "bg-mealHall",
    maxHealth: 20,
    currentHealth: 20,
    damage: 0,
    resourceCosts: { workers: 5, wood: 10, stone: 10, metal: 10 },
    buildScore: 50,
  },
  healingChamber: {
    name: "Healing Chamber",
    symbol: "🩸",
    enabled: false,
    underConstruction: false,
    constructed: false,
    tier: 1,
    /* attackBonus: 0,
    healthBonus: 0, */
    description: "Heals units after combat.",
    bgImage: "bg-healingChamber",
    maxHealth: 25,
    currentHealth: 25,
    damage: 0,
    resourceCosts: { workers: 5, wood: 20, stone: 10, metal: 5 },
    buildScore: 75,
  },
  scoutUnit: {
    name: "Scout Unit",
    symbol: "🔍",
    enabled: false,
    underConstruction: false,
    constructed: false,
    tier: 1,
    /* attackBonus: 0,
    healthBonus: 0, */
    description: "Upgrade intel on the enemy army.",
    bgImage: "bg-scoutUnit",
    maxHealth: 10,
    currentHealth: 10,
    damage: 0,
    resourceCosts: { workers: 10, wood: 15, stone: 15, metal: 15 },
    buildScore: 100,
  },
  crystalQuarry: {
    name: "Crystal Quarry",
    symbol: "⛏️",
    enabled: false,
    underConstruction: false,
    constructed: false,
    tier: 1,
    /* attackBonus: 0,
    healthBonus: 0, */
    description: "Unlocks crystal as a resource.",
    bgImage: "bg-crystal",
    maxHealth: 5,
    currentHealth: 5,
    damage: 0,
    resourceCosts: { workers: 15, wood: 20, stone: 20, metal: 20 },
    buildScore: 125,
    unlockedResource: "crystal",
  },
  goldHoard: {
    name: "Gold Hoard",
    symbol: "🐉",
    enabled: false,
    underConstruction: false,
    constructed: false,
    tier: 1,
    /* attackBonus: 0,
    healthBonus: 0, */
    description: "Unlocks gold as a resource.",
    bgImage: "bg-gold",
    maxHealth: 10,
    currentHealth: 10,
    damage: 0,
    resourceCosts: { workers: 15, wood: 20, stone: 20, metal: 20 },
    buildScore: 100,
    unlockedResource: "gold",
  },
};

/* export const buildingCostsData = {
  swordsmithy: {
    workers: 5,
    wood: 10,
    stone: 10,
    metal: 0,
  },
  // for archer
  archeryHut: {
    workers: 5,
    wood: 10,
    stone: 0,
    metal: 10,
  },
  // for knight
  armorsmithy: {
    workers: 5,
    wood: 0,
    stone: 10,
    metal: 10,
  },
  // for all units
  mealHall: {
    workers: 5,
    wood: 10,
    stone: 10,
    metal: 10,
  },
  healingChamber: {
    workers: 5,
    wood: 10,
    stone: 10,
    metal: 10,
  },
  // for all units
  townCenter: {
    workers: 0,
    wood: 0,
    stone: 0,
    metal: 0,
  },
  scoutUnit: {
    workers: 10,
    wood: 15,
    stone: 15,
    metal: 15,
  },
};
 */
