import { ResourcePool, Resources } from "../types";

export const resourceData: Resources = {
  workers: {
    name: "Worker",
    symbol: "🛠️",
    bgImage: "bg-worker",
    bgImageSm: "bg-workerSm",
    bgImageMd: "bg-workerMd",
    bgImageLg: "bg-workerLg",
  },
  wood: {
    name: "Wood",
    symbol: "🪵",
    bgImage: "bg-wood",
    bgImageSm: "bg-woodSm",
    bgImageMd: "bg-woodMd",
    bgImageLg: "bg-woodLg",
    workers: 0,
    multiplier: 1,
  },
  stone: {
    name: "Stone",
    symbol: "🪨",
    bgImage: "bg-stone",
    bgImageSm: "bg-stoneSm",
    bgImageMd: "bg-stoneMd",
    bgImageLg: "bg-stoneLg",
    workers: 0,
    multiplier: 1,
  },
  metal: {
    name: "Metal",
    symbol: "🔩",
    bgImage: "bg-metal",
    bgImageSm: "bg-metalSm",
    bgImageMd: "bg-metalMd",
    bgImageLg: "bg-metalLg",
    workers: 0,
    multiplier: 1,
  },
  crystal: {
    name: "Crystal",
    symbol: "💎",
    bgImage: "bg-crystal",
    bgImageSm: "bg-crystalSm",
    bgImageMd: "bg-crystalMd",
    bgImageLg: "bg-crystalLg",
    workers: 0,
    multiplier: 1,
  },
  gold: {
    name: "Gold",
    symbol: "🪙",
    bgImage: "bg-gold",
    bgImageSm: "bg-goldSm",
    bgImageMd: "bg-goldMd",
    bgImageLg: "bg-goldLg",
    workers: 0,
    multiplier: 1,
  },
};

export const resourcePoolData: ResourcePool = {
  workers: 5,
  wood: 0,
  stone: 0,
  metal: 0,
  crystal: 0,
  gold: 0,
};
