export const resourceData = {
  freeworkers: {
    collected: 5,
    name: "Freeworker",
    resourceSymbol: "🛠️",
    description:
      "Used when gathering resources, training units, and constructing buildings",
  },
  wood: {
    collected: 0,
    name: "Wood",
    resourceSymbol: "🪵",
    workers: 0,
    workersNeeded: 1,
    workerName: "Woodcutters",
    workerType: "woodcutters",
    workerSymbol: "🪓",
    description: "Collects 1🪵.",
  },
  stone: {
    collected: 0,
    name: "Stone",
    resourceSymbol: "🪨",
    workers: 0,
    workersNeeded: 1,
    workerName: "Stonemasons",
    workerType: "stonemasons",
    workerSymbol: "⚒️",
    description: "Collects 1🪨.",
  },
  metal: {
    collected: 0,
    name: "Metal",
    resourceSymbol: "🔩",
    workers: 0,
    workersNeeded: 1,
    workerName: "Metalworkers",
    workerType: "metalworkers",
    workerSymbol: "🥽",
    description: "Collects 1🔩.",
  },
};
