export { default as About } from "./About";
export { default as HowToPlay } from "./HowToPlay";
export { default as Leaderboards } from "./Leaderboards";
export { default as MenuInput } from "./MenuInput";
export { default as MenuItem } from "./MenuItem";
export { default as MenuTitle } from "./MenuTitle";
export { default as Options } from "./Options";
export { default as Play } from "./Play";
export { default as PopupModal } from "./PopupModal";
